-- 1. Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL,
  description TEXT,
  image TEXT,
  image2 TEXT,
  stock INTEGER DEFAULT 0,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Visitors Table (Analytics)
CREATE TABLE visitors (
  session_id UUID PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_active TIMESTAMPTZ DEFAULT NOW(),
  location_city TEXT,
  location_country TEXT,
  ip_address TEXT, -- Store raw IP for persistence logic
  ip_mask TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  nickname TEXT -- Admin-assigned display name for this visitor
);

-- 3. Messages Table (Real-time Chat)
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  session_id UUID REFERENCES visitors(session_id),
  sender TEXT NOT NULL, -- 'user', 'admin', or 'bot'
  text TEXT NOT NULL,
  delivered BOOLEAN DEFAULT FALSE, -- WhatsApp-style status
  is_read BOOLEAN DEFAULT FALSE    -- WhatsApp-style status
);

-- Enable Realtime for these tables (Run this in Supabase SQL Editor if not already enabled)
-- ALTER PUBLICATION supabase_realtime ADD TABLE messages;
-- ALTER PUBLICATION supabase_realtime ADD TABLE visitors;

-- 4. Notifications Table (Global Broadcasts)
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  message TEXT NOT NULL,
  type TEXT DEFAULT 'info', -- 'info', 'success', 'warning'
  target_session_id UUID REFERENCES visitors(session_id) -- NULL for global broadcast
);

-- Security Note: 
-- You will need to enable Row Level Security (RLS) if you plan to move beyond a development environment.
-- For initial setup, you can disable RLS or set permissive policies for the anonymous role.
